services:
  - type: web
    name: weather-app
    env: docker
    buildCommand: docker build -t weather-app .
    startCommand: docker run --env-file .env -p 7000:7000 -d weather-app
    plan: free
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
